# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Package - Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm i
          npm run dashboard
          mkdir /tmp/prometheus-snaphost
          cp package.json /tmp/prometheus-snaphost
          cp -r src/* /tmp/prometheus-snaphost
          cp -r node_modules/* /tmp/prometheus-snaphost
          tar -C /tmp -zcf prometheus-snaphost.tar.gz ./prometheus-snaphost
          ls -l /tmp
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: prometheus-snaphost.tar.gz
          # A file, directory or wildcard pattern that describes what to upload
          path: prometheus-snaphost.tar.gz
          if-no-files-found: error